# ============================================================================
#  FF7 Rebirth - DLSS 5 Neural Rendering (RenodX) - Uninstaller
#
#  Removes what install.ps1 added:
#    - renodx-dlss5-v2.5.addon64
#    - renodx-ff7rebirth.addon64           (kept only with -KeepRenoDX)
#    - the NVIDIA 310.8 files: 11 nvngx_*/sl.* DLLs + 3 license txts
#      (kept only with -KeepNvidiaDlls)
#    - restores your original ReShade.ini (from ReShade.ini.dlss5kit.bak)
#      (when no backup exists it just removes our LoadFromDllMain entry)
#    - removes the generated uninstall-dlss5.ps1
#
#  ReShade itself (d3d12.dll & co.) is NOT removed - it is a general tool
#  and other mods may use it.  To remove ReShade too, run the ReShade
#  uninstaller separately (ReShade_Setup.exe --state uninstall).
#
#  Usage:  uninstall-dlss5.bat (generated by the installer)
#          or: powershell -ExecutionPolicy Bypass -File uninstall.ps1
#                [-GameDir <path>] [-KeepRenoDX] [-KeepNvidiaDlls] [-Yes]
# ============================================================================
#Requires -Version 5.1

param(
    [string]$GameDir = "",
    [switch]$KeepRenoDX,
    [switch]$KeepNvidiaDlls,
    [switch]$Yes
)

$ErrorActionPreference = 'Stop'
$script:Yes = [bool]$Yes
$script:DlssFile   = 'renodx-dlss5-v2.5.addon64'
$script:MainFile   = 'renodx-ff7rebirth.addon64'
# The complete NVIDIA Streamline/DLSS 310.8 set (14 files): 11 runtime DLLs
# + 3 license files (matches what install.ps1 installs).
$script:NvidiaFiles = @(
    'nvngx_dlss.dll','nvngx_dlssg.dll','nvngx_dlssnr.dll',
    'sl.common.dll','sl.dlss.dll','sl.dlss_g.dll','sl.dlss_nr.dll',
    'sl.interposer.dll','sl.nis.dll','sl.pcl.dll','sl.reflex.dll',
    'nis.license.txt','nvngx_dlss.license.txt','reflex.license.txt'
)

Write-Host ""
Write-Host "FF7 Rebirth - DLSS 5 (RenodX) Uninstaller" -ForegroundColor Magenta

# ---------------------------- game detection -------------------------------
function Resolve-GamePaths([string]$path) {
    if (-not $path) { return $null }
    if (Test-Path $path -PathType Leaf) {
        if ((Split-Path $path -Leaf) -eq 'ff7rebirth_.exe') {
            $win64 = Split-Path $path -Parent
            if ($win64 -like '*\End\Binaries\Win64') {
                return [pscustomobject]@{ Root = (Split-Path (Split-Path (Split-Path $win64))); Win64 = $win64 }
            }
            return [pscustomobject]@{ Root = $null; Win64 = $win64 }
        }
        return $null
    }
    if (Test-Path $path -PathType Container) {
        if (Test-Path (Join-Path $path 'End\Binaries\Win64\ff7rebirth_.exe')) {
            return [pscustomobject]@{ Root = $path; Win64 = (Join-Path $path 'End\Binaries\Win64') }
        }
        if (Test-Path (Join-Path $path 'ff7rebirth_.exe')) {
            if ($path -like '*\End\Binaries\Win64') {
                return [pscustomobject]@{ Root = (Split-Path (Split-Path (Split-Path $path))); Win64 = $path }
            }
            return [pscustomobject]@{ Root = $null; Win64 = $path }
        }
    }
    return $null
}

function Get-SteamRoots {
    $roots = @()
    $steamPath = $null
    try {
        $steamKey = Get-ItemProperty 'HKCU:\Software\Valve\Steam' -ErrorAction SilentlyContinue
        if ($steamKey) {
            $steamPath = $steamKey.SteamPath
            if (-not $steamPath) { $steamPath = $steamKey.InstallPath }
        }
    } catch {}
    if ($steamPath) { $steamPath = ($steamPath -replace '/', '\').TrimEnd('\') }
    if ($steamPath -and (Test-Path $steamPath)) {
        $roots += $steamPath
        $vdf = Join-Path $steamPath 'steamapps\libraryfolders.vdf'
        if (Test-Path $vdf) {
            foreach ($line in (Get-Content $vdf)) {
                if ($line -match '^\s*"path"\s+"(.+?)"\s*$') {
                    $r = $Matches[1] -replace '\\\\', '\'
                    if (Test-Path (Join-Path $r 'steamapps')) { $roots += $r }
                }
                elseif ($line -match '^\s*"\d+"\s+"(.+?)"\s*$') {
                    $r = $Matches[1] -replace '\\\\', '\'
                    if (Test-Path (Join-Path $r 'steamapps')) { $roots += $r }
                }
            }
        }
    }
    return ($roots | Select-Object -Unique)
}

function Get-GamePaths {
    if ($GameDir) {
        $r = Resolve-GamePaths $GameDir
        if ($r) { return $r }
        Write-Host "  [!] Could not validate the -GameDir path: $GameDir" -ForegroundColor Yellow
    }
    if ($PSScriptRoot) {
        $r = Resolve-GamePaths $PSScriptRoot
        if ($r) { return $r }
    }
    foreach ($sr in (Get-SteamRoots)) {
        $r = Resolve-GamePaths (Join-Path $sr 'steamapps\common\FINAL FANTASY VII REBIRTH')
        if ($r) { return $r }
    }
    $drives = @()
    try { $drives = (Get-PSDrive -PSProvider FileSystem).Root } catch {}
    foreach ($d in $drives) {
        foreach ($base in @("$d`SteamLibrary\steamapps\common", "$d`Games", "$d`GOG Games", "$d`Program Files", "$d`Program Files (x86)", $d)) {
            $r = Resolve-GamePaths (Join-Path $base 'FINAL FANTASY VII REBIRTH')
            if ($r) { return $r }
        }
    }
    return $null
}

$paths = Get-GamePaths
if (-not $paths) {
    Write-Host "Game folder not found automatically. Paste the game folder path below (or 'q' to quit)." -ForegroundColor Yellow
    while (-not $paths) {
        $try = Read-Host "Path to the game folder (containing End\Binaries\Win64\ff7rebirth_.exe)"
        if ($try -match '^[Qq]$') { Write-Host "Cancelled."; exit 0 }
        $paths = Resolve-GamePaths $try
    }
}
$script:Win64 = $paths.Win64
$reshadeIni  = Join-Path $script:Win64 'ReShade.ini'
Write-Host "  [i] Uninstalling from: $($script:Win64)" -ForegroundColor Cyan

# --- addons -------------------------------------------------------------
if (Test-Path (Join-Path $script:Win64 $script:DlssFile)) {
    Remove-Item (Join-Path $script:Win64 $script:DlssFile) -Force
    Write-Host "  [OK] removed $script:DlssFile" -ForegroundColor Green
}
if (-not $KeepRenoDX -and (Test-Path (Join-Path $script:Win64 $script:MainFile))) {
    Remove-Item (Join-Path $script:Win64 $script:MainFile) -Force
    Write-Host "  [OK] removed $script:MainFile" -ForegroundColor Green
}
elseif (Test-Path (Join-Path $script:Win64 $script:MainFile)) {
    Write-Host "  [i] kept renodx-ff7rebirth.addon64 (-KeepRenoDX)" -ForegroundColor Cyan
}

# --- nvidia dlls ---------------------------------------------------------
if (-not $KeepNvidiaDlls) {
    foreach ($dll in $script:NvidiaFiles) {
        $p = Join-Path $script:Win64 $dll
        if (Test-Path $p) {
            Remove-Item $p -Force
            Write-Host "  [OK] removed $dll" -ForegroundColor Green
        }
    }
}
else {
    Write-Host "  [i] kept the nvngx_*/sl.* DLLs (-KeepNvidiaDlls)" -ForegroundColor Cyan
}

# --- reshade.ini ---------------------------------------------------------
$iniBackup = "$reshadeIni.dlss5kit.bak"
if (Test-Path $reshadeIni) {
    if (Test-Path $iniBackup) {
        Copy-Item $iniBackup $reshadeIni -Force
        Write-Host "  [OK] ReShade.ini restored from backup" -ForegroundColor Green
    }
    else {
        $lines = [System.IO.File]::ReadAllLines($reshadeIni)
        $keyPrefix = 'LoadFromDllMain='
        $changed = $false
        for ($i = 0; $i -lt $lines.Count; $i++) {
            if ($lines[$i].StartsWith($keyPrefix)) {
                $value = $lines[$i].Substring($keyPrefix.Length)
                $entries = @(); $cur = ''
                foreach ($ch in $value.ToCharArray()) {
                    if ([int]$ch -eq 0) { $entries += $cur; $cur = '' } else { $cur += $ch }
                }
                $entries += $cur
                $kept = @($entries | Where-Object { $_ -ne $script:DlssFile })
                if ($kept.Count -ne $entries.Count) {
                    if ($kept.Count -gt 0) { $lines[$i] = $keyPrefix + ($kept -join [string][char]0) }
                    else { $lines[$i] = $null }
                    $changed = $true
                }
            }
        }
        if ($changed) {
            $lines = @($lines | Where-Object { $_ -ne $null })
            [System.IO.File]::WriteAllLines($reshadeIni, $lines)
            Write-Host "  [OK] removed our LoadFromDllMain entry from ReShade.ini" -ForegroundColor Green
        }
        else {
            Write-Host "  [i] ReShade.ini left as-is (no backup, no entry to remove)" -ForegroundColor Cyan
        }
    }
    if (Test-Path $iniBackup) {
        Remove-Item $iniBackup -Force
        Write-Host "  [OK] removed the ini backup file" -ForegroundColor Green
    }
}
else {
    Write-Host "  [i] no ReShade.ini found" -ForegroundColor Cyan
}

# --- generated helper files ----------------------------------------------
$genPs1 = Join-Path $PSScriptRoot 'uninstall-dlss5.ps1'
if ($PSScriptRoot -and (Test-Path $genPs1)) {
    Remove-Item $genPs1 -Force
    Write-Host "  [OK] removed generated uninstall-dlss5.ps1" -ForegroundColor Green
}

Write-Host ""
Write-Host "Done. You can close this window." -ForegroundColor Green
Write-Host "(you can also delete uninstall-dlss5.bat / install.bat from the game folder now)" -ForegroundColor DarkGray